import pytest_rerunfailures


def test_failure_rerun():
    assert 2+2 == 5